package oauth

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/mudler/nib/provider"
)

// userAgent identifies nib to OAuth/token endpoints.
const userAgent = "nib/1.0"

// TokenResponse is the result of a token exchange or refresh. The fields map
// to standard OAuth 2.0 token endpoint responses.
type TokenResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int    `json:"expires_in"`
	TokenType    string `json:"token_type"`
	Scope        string `json:"scope"`
}

// Identity is the account/org info recovered after a token exchange.
type Identity struct {
	AccountID string
	Email    string
	OrgID    string
	OrgName  string
}

// AuthorizeURL builds the authorization-code flow URL for the user to open.
// The provider's AuthorizeURL, ClientID, Scopes, and AuthorizeParams are
// taken from def; challenge and state are generated by the caller (pkce.go).
func AuthorizeURL(def provider.Definition, challenge, state, redirectURI string) string {
	q := url.Values{}
	q.Set("response_type", "code")
	q.Set("client_id", def.EffectiveClientID())
	q.Set("redirect_uri", redirectURI)
	q.Set("scope", strings.Join(def.Scopes, " "))
	q.Set("code_challenge", challenge)
	q.Set("code_challenge_method", ChallengeMethod)
	q.Set("state", state)
	for k, v := range def.AuthorizeParams {
		q.Set(k, v)
	}
	return def.AuthorizeURL + "?" + q.Encode()
}

// Exchange trades an authorization code for access and refresh tokens.
// codeVerifier must match the challenge sent in AuthorizeURL. If def has a
// ClientSecret, it is included in the request (required by confidential
// clients like Google).
func Exchange(ctx context.Context, def provider.Definition, code, codeVerifier, redirectURI, state string) (TokenResponse, error) {
	body := map[string]string{
		"grant_type":    "authorization_code",
		"client_id":     def.EffectiveClientID(),
		"code":          code,
		"code_verifier": codeVerifier,
		"redirect_uri":  redirectURI,
		"state":         state,
	}
	if sec := def.EffectiveClientSecret(); sec != "" {
		body["client_secret"] = sec
	}
	return postToken(ctx, def, body)
}

// Refresh exchanges a refresh token for a new access token. The new response
// may include a new refresh_token (rotation); the caller should persist it.
func Refresh(ctx context.Context, def provider.Definition, refreshToken string) (TokenResponse, error) {
	body := map[string]string{
		"grant_type":    "refresh_token",
		"client_id":     def.EffectiveClientID(),
		"refresh_token": refreshToken,
	}
	if len(def.Scopes) > 0 {
		body["scope"] = strings.Join(def.Scopes, " ")
	}
	if sec := def.EffectiveClientSecret(); sec != "" {
		body["client_secret"] = sec
	}
	return postToken(ctx, def, body)
}

// postToken POSTs to the token endpoint and parses the response. The body
// format (JSON or form-encoded) and extra headers are taken from def.
func postToken(ctx context.Context, def provider.Definition, body map[string]string) (TokenResponse, error) {
	req, err := newRequest(ctx, http.MethodPost, def.TokenURL, body, def)
	if err != nil {
		return TokenResponse{}, fmt.Errorf("oauth: create token request: %w", err)
	}

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return TokenResponse{}, fmt.Errorf("oauth: token request: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return TokenResponse{}, fmt.Errorf("oauth: read token response: %w", err)
	}
	if resp.StatusCode != http.StatusOK {
		return TokenResponse{}, fmt.Errorf("oauth: token endpoint returned %d: %s", resp.StatusCode, strings.TrimSpace(string(respBody)))
	}

	var tr TokenResponse
	if err := json.Unmarshal(respBody, &tr); err != nil {
		return TokenResponse{}, fmt.Errorf("oauth: parse token response: %w", err)
	}
	return tr, nil
}

// newRequest creates an HTTP request with the standard headers and body
// encoding. The body is form-encoded if def.TokenBodyFormat is "form", JSON
// otherwise. ExtraTokenHeaders are applied on top of the standard headers.
func newRequest(ctx context.Context, method, target string, body map[string]string, def provider.Definition) (*http.Request, error) {
	var reqBody io.Reader
	if def.TokenBodyFormat == "form" {
		form := url.Values{}
		for k, v := range body {
			form.Set(k, v)
		}
		reqBody = strings.NewReader(form.Encode())
	} else {
		data, err := json.Marshal(body)
		if err != nil {
			return nil, fmt.Errorf("oauth: marshal request: %w", err)
		}
		reqBody = bytes.NewReader(data)
	}

	req, err := http.NewRequestWithContext(ctx, method, target, reqBody)
	if err != nil {
		return nil, err
	}
	if def.TokenBodyFormat == "form" {
		req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	} else {
		req.Header.Set("Content-Type", "application/json")
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("User-Agent", userAgent)
	for k, v := range def.ExtraTokenHeaders {
		req.Header.Set(k, v)
	}
	return req, nil
}

// FetchIdentity recovers account info after a token exchange. It dispatches
// based on def.IdentityMethod: "bootstrap" calls Anthropic's claude_cli
// endpoint, "userinfo" calls a standard OIDC userinfo endpoint. Returns a
// zero Identity (no error) if IdentityURL is empty.
func FetchIdentity(ctx context.Context, def provider.Definition, accessToken string) (Identity, error) {
	if def.IdentityURL == "" {
		return Identity{}, nil
	}
	switch def.IdentityMethod {
	case "userinfo":
		return fetchUserinfo(ctx, def, accessToken)
	case "bootstrap":
		return bootstrapIdentity(ctx, def, accessToken)
	default:
		return Identity{}, nil
	}
}

// fetchUserinfo calls a standard OIDC userinfo endpoint. The response is
// expected to have "email" and "sub" (account ID) fields.
func fetchUserinfo(ctx context.Context, def provider.Definition, accessToken string) (Identity, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, def.IdentityURL, nil)
	if err != nil {
		return Identity{}, fmt.Errorf("oauth: create userinfo request: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+accessToken)
	req.Header.Set("Accept", "application/json")
	req.Header.Set("User-Agent", userAgent)

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return Identity{}, fmt.Errorf("oauth: userinfo request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return Identity{}, fmt.Errorf("oauth: userinfo returned %d", resp.StatusCode)
	}

	var raw struct {
		Email string `json:"email"`
		Sub   string `json:"sub"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&raw); err != nil {
		return Identity{}, fmt.Errorf("oauth: parse userinfo: %w", err)
	}
	return Identity{AccountID: raw.Sub, Email: raw.Email}, nil
}

// bootstrapIdentity calls Anthropic's claude_cli/bootstrap endpoint to recover
// account and organization info. The response shape is Anthropic-specific.
func bootstrapIdentity(ctx context.Context, def provider.Definition, accessToken string) (Identity, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, def.IdentityURL, nil)
	if err != nil {
		return Identity{}, fmt.Errorf("oauth: create bootstrap request: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+accessToken)
	req.Header.Set("User-Agent", userAgent)
	for k, v := range def.ExtraTokenHeaders {
		req.Header.Set(k, v)
	}

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return Identity{}, fmt.Errorf("oauth: bootstrap request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return Identity{}, fmt.Errorf("oauth: bootstrap returned %d", resp.StatusCode)
	}

	var raw bootstrapResponse
	if err := json.NewDecoder(resp.Body).Decode(&raw); err != nil {
		return Identity{}, fmt.Errorf("oauth: parse bootstrap: %w", err)
	}

	id := Identity{
		AccountID: raw.Account.UUID,
		Email:     raw.Account.EmailAddress,
	}
	if len(raw.Organizations) > 0 {
		id.OrgID = raw.Organizations[0].UUID
		id.OrgName = raw.Organizations[0].Name
	}
	return id, nil
}

// bootstrapResponse is the subset of the Anthropic bootstrap endpoint's JSON.
type bootstrapResponse struct {
	Account struct {
		UUID         string `json:"uuid"`
		EmailAddress string `json:"email_address"`
	} `json:"account"`
	Organizations []struct {
		UUID string `json:"uuid"`
		Name string `json:"name"`
	} `json:"organizations"`
}

// ExpiresAt converts an expires_in seconds value to an absolute time.
func ExpiresAt(expiresIn int) time.Time {
	if expiresIn <= 0 {
		return time.Time{}
	}
	return time.Now().Add(time.Duration(expiresIn) * time.Second)
}
